// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

/*
 * Nomad
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.1.4
 * Contact: support@hashicorp.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize, Default)]
pub struct Resources {
    #[serde(rename = "cpu", skip_serializing_if = "Option::is_none")]
    pub cpu: Option<i32>,
    #[serde(rename = "Cores", skip_serializing_if = "Option::is_none")]
    pub cores: Option<i32>,
    #[serde(rename = "Devices", skip_serializing_if = "Option::is_none")]
    pub devices: Option<Vec<crate::models::RequestedDevice>>,
    #[serde(rename = "DiskMB", skip_serializing_if = "Option::is_none")]
    pub disk_mb: Option<i32>,
    #[serde(rename = "iops", skip_serializing_if = "Option::is_none")]
    pub iops: Option<i32>,
    #[serde(rename = "MemoryMB", skip_serializing_if = "Option::is_none")]
    pub memory_mb: Option<i32>,
    #[serde(rename = "MemoryMaxMB", skip_serializing_if = "Option::is_none")]
    pub memory_max_mb: Option<i32>,
    #[serde(rename = "Networks", skip_serializing_if = "Option::is_none")]
    pub networks: Option<Vec<crate::models::NetworkResource>>,
}

impl Resources {
    pub fn new() -> Resources {
        Resources {
            cpu: None,
            cores: None,
            devices: None,
            disk_mb: None,
            iops: None,
            memory_mb: None,
            memory_max_mb: None,
            networks: None,
        }
    }
}


